add horizontal drag to seek feature
jhomlala/betterplayer pull request #97
Opened 2020-10-21 09:47 UTC by r6c

2020-10-21 18:26 UTC, jhomlala commented
@r6c 
Please provide more details what it does, what is purpose, maybe some screenshot/videos?

2020-10-22 03:13 UTC, r6c commented
@jhomlala 
![Wondershare UniConverter_000001](https://user-images.githubusercontent.com/45527749/96819993-8c179c80-1457-11eb-95e5-db9e9eb6b016.GIF)

2020-10-24 13:21 UTC, jhomlala requested changes

2020-10-24 13:21 UTC, jhomlala commented on lib/src/controls/better_player_clickable_widget.dart
> +      child: GestureDetector(
Why did you change from InkWell to GestureDetector? InkWell was intentional here, because we show user ripple effect.

2020-10-24 13:21 UTC, jhomlala commented on lib/src/controls/better_player_material_controls.dart
> +        onHorizontalDragStart: (_) {
This code seems to be same as cupertino one. Can you create some shared class? DRY rule is broken here.

2020-10-24 13:21 UTC, jhomlala commented on lib/src/controls/better_player_material_controls.dart
> +  double _getHorizontalValuePercent(double movePan, double layoutWidth) {
Same as above. DRY.

2020-10-24 13:21 UTC, jhomlala commented on lib/src/controls/better_player_cupertino_controls.dart
> +  Duration _currentPosition;
Do we really need this here?

2020-10-24 13:21 UTC, jhomlala commented on lib/src/controls/better_player_cupertino_controls.dart
> +  double _movePan = 0;
Please add comment describing what it is.

2020-11-04 21:47 UTC, jhomlala commented
@r6c Can you fix reported issues?

2020-11-29 10:23 UTC, jhomlala commented
@r6c any update?

2021-01-09 14:54 UTC, jhomlala commented
Closed due to no activity. Feel free to anwser and I'll reopen it.

2021-01-09 14:54 UTC, closed without merging